name: Unit Tests

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: npm install
      - name: Test
        run: npm run test:unit
